
Animal.create(name: "bat", url: "bat4.jpg")
Animal.create(name: "cat", url: "cat_14.jpg")
Animal.create(name: "dog", url: "dog5.jpg")
Animal.create(name: "duck", url: "duck4.jpg")
Animal.create(name: "fish", url: "fish8.jpg")
Animal.create(name: "fox", url: "fox3.jpg")
Animal.create(name: "frog", url: "frog4.jpg")
Animal.create(name: "goat", url: "goat1.jpg")
Animal.create(name: "lion", url: "lion1.jpg")
Animal.create(name: "yak", url: "yak2.jpg")
Animal.create(name: "african elephant", url: "african_elephant.jpg")
Animal.create(name: "arctic fox", url: "arctic_fox_11.jpg")
Animal.create(name: "asian black bear", url: "asian_black_bear5.jpg")
Animal.create(name: "badger", url: "badger2.jpg")
Animal.create(name: "beaver", url: "beaver3.jpg")
Animal.create(name: "camel", url: "camel2.jpg")
Animal.create(name: "cougar", url: "cougar.jpg")
Animal.create(name: "donkey", url: "donkey3.jpg")
Animal.create(name: "dragon", url: "dragon3.jpg")
Animal.create(name: "eagle", url: "eagle1.jpg")
Animal.create(name: "echidna", url: "echidna7.jpg")
Animal.create(name: "electric eel", url: "electric_eel3.jpg")
Animal.create(name: "geese", url: "geese3.jpg")
Animal.create(name: "goat", url: "goat1.jpg")
Animal.create(name: "gorilla", url: "gorilla4.jpg")
Animal.create(name: "hamster", url: "hamster3.jpg")
Animal.create(name: "hippo", url: "hippo4.jpg")
Animal.create(name: "horse", url: "horse4.jpg")
Animal.create(name: "iguana", url: "iguana4.jpg")
Animal.create(name: "indian palm squirrel", url: "indian_palm_squirrel9.jpg")
Animal.create(name: "insects", url: "insects3.jpg")
Animal.create(name: "jackal", url: "jackal1.jpg")
Animal.create(name: "jaguar", url: "jaguar6.jpg")
Animal.create(name: "jellyfish", url: "jellyfish4.jpg")
Animal.create(name: "kangaroo", url: "kangaroo3.jpg")
Animal.create(name: "killer whale", url: "killer_whale_3.jpg")
Animal.create(name: "king crab", url: "king_crab1.jpg")
Animal.create(name: "lemmings", url: "lemmings.jpg")
Animal.create(name: "lizard", url: "lizard4.jpg")
Animal.create(name: "monkey", url: "monkey9.jpg")
Animal.create(name: "moth", url: "moth.jpg")
Animal.create(name: "mouse", url: "mouse1.jpg")
Animal.create(name: "neanderthal", url: "neanderthal.png")
Animal.create(name: "newt", url: "newt1.jpg")
Animal.create(name: "nightingale", url: "nightingale1.jpg")
Animal.create(name: "octopus", url: "octopus1.jpg")
Animal.create(name: "orangutan", url: "orang-utan.jpg")
Animal.create(name: "otter", url: "otter_11.jpg")
Animal.create(name: "penguin", url: "penguin5.jpg")
Animal.create(name: "platypus", url: "platypus_7.jpg")
Animal.create(name: "pygmy marmoset", url: "pygmy_marmoset.jpg")
Animal.create(name: "rattlesnake", url: "rattlesnake3.jpg")
Animal.create(name: "red knee tarantula", url: "red_knee_tarantula.jpg")
Animal.create(name: "rhino", url: "rhino8.jpg")
Animal.create(name: "scorpion", url: "scorpion2.jpg")
Animal.create(name: "sea lion", url: "sea_lion10.jpg")
Animal.create(name: "skunk", url: "skunk6.jpg")
Animal.create(name: "swan", url: "swan6.jpg")
Animal.create(name: "termite", url: "termite3.jpg")


